"""add_clinical_sessions

Revision ID: b439265eefc9
Revises: 49b21f9d6e64
Create Date: 2026-04-11 17:21:16.130759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b439265eefc9'
down_revision: Union[str, None] = '49b21f9d6e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_plan_id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_plan_id'], ['execution_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_sessions_execution_plan_id'), ['execution_plan_id'], unique=False)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_test_sessions_clinical_session_id'), ['clinical_session_id'], unique=False)
        batch_op.create_foreign_key('fk_test_sessions_clinical_session_id', 'clinical_sessions', ['clinical_session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_sessions_clinical_session_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_test_sessions_clinical_session_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('clinical_session_id')

    with op.batch_alter_table('clinical_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_sessions_execution_plan_id'))

    op.drop_table('clinical_sessions')
    # ### end Alembic commands ###
